name: Documentation

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - "*.md"
  pull_request:
    branches: [main]
    paths:
      - "docs/**"
      - "*.md"

jobs:
  check-links:
    name: Check Documentation Links
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check links
        uses: gaurav-nelson/github-action-markdown-link-check@3c3b66f1f7d0900e37b71eca45b63ea9eedfce31 # 1.0.17
        with:
          use-quiet-mode: "yes"
          config-file: ".github/markdown-link-check-config.json"
        continue-on-error: true

  spell-check:
    name: Spell Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Spell check
        uses: streetsidesoftware/cspell-action@e0668cf020899e887ee8ad4d173c31738a79eae8 # v9.0.1
        with:
          files: |
            **/*.md
            **/*.swift
          config: ".github/cspell.json"
        continue-on-error: true
